HelpMessage:
  - "YOU HIT ME YOU DIE PLUGIN:"
  - "permission: youhitmeyoudie.* can access all commands"
  - "/youhitmeyoudie add <playerName> to add a player to the list"
  - "permission: youhitmeyoudie.add"
  - "/youhitmeyoudie remove <playerName> to remove a play from the list"
  - "permission: youhitmeyoudie.remove"
  - "/youhitmeyoudie list to show list of added players"
  - "permission: youhitmeyoudie.list"
  - "/youhitmeyoudie reload to reload the plugin"
  - "permission: youhitmeyoudie.reload"
ReloadMessage: "Plugin YouHitMeYouDie is reloaded, have fun"
RemoveMessage: "You remove %player% from the list"
NotInListMessage: "%player% isn't in list to remove"
AddMessage: "You add %player% to the list"
InListMessage: "%player% is already in list"
NotOnlineMessage: "%player% is not online right now"
NullPlayerMessage: "%player% isn't exist in your server"
PlayersUsingYouKillMeYouDie:
